### ISSUE TITLE
[1.12] Texture for Forestry Copper dust is generic (checker pattern)

### ISSUE THREAD

**Issue by donqixot** [oitsjustjose/Pulver#4]
Thank you very much for this mod!

I am trying together Actually Additions and Forestry. Copper dust is generated by Pulver, but texture is generic (checker pattern). Is there anything I need to add or modify in config? 

I am using Forestry 1.12-5.4.2.124, Actually Additions 1.12-r113, Forge 14.21.1.2387, JEI 1.12-4.7.0.68, Pulver 1.12-1.0a.

**Comment by oitsjustjose** [comment]
I had a release with messed up textures, but the new ones should be fine. Re-download Pulver (it'll be the same version number), that should have working textures. Let me know if it works!

**Comment by donqixot** [comment]
Thanks! I redownloaded, replaced file. Now I see the dusts properly, but they are not added to recipe for the AA Crusher. Tooltip says "added for Forestry", which is good. Funny part is previously it was added for recipe, just texture was wrong.

**Comment by oitsjustjose** [comment]
The "Added for <x>" means "This dust was added because <x> mod adds an ore and an ingot". 

So, "Added for Forestry" means that Forestry's addition of <y> ore and <y> ingot triggered <y> dust. I don't know why AA wouldn't be adding it to the Crusher recipe.. you say it worked before but doesn't work now?

**Comment by donqixot** [comment]
Exactly. I just tried again, restored the version I downloaded earlier, replaced. I now see the recipe, but texture is wrong. Thanks for quick response, appreciate!

**Comment by oitsjustjose** [comment]
That's odd, I can't figure what would've changed - I'll look and see if it's that I'm registering my dusts to the ore dictionary AFTER AA has looked in the Ore Dictionary for recipe candidates..
