### ISSUE TITLE
[1.12.1] Crash when mousing over dust from removed mod IC2

### ISSUE THREAD

**Issue by MokahTGS** [oitsjustjose/Pulver#5]
Got a crash when mousing over a dust from a IC2 that had been removed.  The dust was still there but with a broken texture.  I was going to delete it but the game crashed when I moused over it.

https://pastebin.com/iFZy6vJp

**Comment by MokahTGS** [comment]
Well it's not IC2 or at least not entirely.  These dust item persist even when I remove Furnus as a mod.  Not sure what to do as this makes this world unplayable.

**Comment by oitsjustjose** [comment]
Working on a fix ASAP, thanks for the report!

**Comment by oitsjustjose** [comment]
Can you try [this build](https://puu.sh/xC5WW/fb8740441a.jar) and see if it works?

**Comment by MokahTGS** [comment]
I will bit most likely not until tomorrow

**Comment by MokahTGS** [comment]
Nope still crashing: https://pastebin.com/qghT7Ky8

**Comment by oitsjustjose** [comment]
Fixed; update coming to CurseForge!
