### ISSUE TITLE
Request: Bronze dust?

### ISSUE THREAD

**Issue by Gelles** [oitsjustjose/Pulver#6]
Playing a custom 1.12 world with Immersive Engineering and Forestry as the only two tech mods, and Geolosys as the ore management. Realized IE doesn't add its own tin or tin grit, so I added Pulver so I could make some copper grit+tin dust=bronze dust crafttweaker recipes for early bronze before I have an alloy kiln...

But there's no bronze dust. >.< 

Since there's no config, can I request bronze dust?

**Comment by oitsjustjose** [comment]
Sorry, the point of Pulver is to add dusts for *ores* that aren't already added - not for other ingots or blends.

**Comment by Gelles** [comment]
No problem. Thought I'd ask. Thank you!
